spring: 

 datasource: 
  url: jdbc:oracle:thin:@localhost:1521/XE
  username: ojtUser
  password: root
  driverClassName: oracle.jdbc.OracleDriver

server:
  port: 9090
  
  multipart:
    maxFileSize: 10Mb
    maxRequestSize: 10Mb
  
  